USE ROLE ACCOUNTADMIN;
-- --------------------------------------------THIS BELOW COMMAND CAN ONLY RUN BY ACCOUNT ADMIN--------------------------------------------
-- Tạo roles
CREATE ROLE IF NOT EXISTS TuanTD24_ROLE;
CREATE ROLE IF NOT EXISTS DucPB7_ROLE;

-- Tạo users (khuyến nghị dùng KEY-PAIR thay vì password nếu có thể)
CREATE OR REPLACE USER TuanTD24
  PASSWORD = 'supernova'
  DEFAULT_ROLE = TuanTD24_ROLE
  DEFAULT_WAREHOUSE = TRANSFORMING
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service account for mini project OTJ';

CREATE OR REPLACE USER DucPB7
  PASSWORD = 'bigbang'
  DEFAULT_ROLE = DucPB7_ROLE
  DEFAULT_WAREHOUSE = TRANSFORMING
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service account for mini project OTJ';

GRANT USAGE ON WAREHOUSE TRANSFORMING TO ROLE TuanTD24_ROLE;
GRANT USAGE ON WAREHOUSE compute_wh TO ROLE TuanTD24_ROLE;
GRANT USAGE ON DATABASE dvd_rental TO ROLE TuanTD24_ROLE;
GRANT CREATE SCHEMA ON DATABASE dvd_rental TO ROLE TuanTD24_ROLE;
GRANT CREATE TABLE ON SCHEMA dvd_rental.bronze TO ROLE TuanTD24_ROLE;
GRANT CREATE TABLE ON SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT CREATE TABLE ON SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;
GRANT CREATE VIEW ON SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT CREATE VIEW ON SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;
GRANT CREATE STAGE ON SCHEMA dvd_rental.bronze TO ROLE TuanTD24_ROLE;
GRANT CREATE STAGE ON SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT CREATE STAGE ON SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;


GRANT ALL PRIVILEGES ON SCHEMA dvd_rental.bronze TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dvd_rental.bronze TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON ALL STREAMS IN SCHEMA dvd_rental.bronze TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON ALL STREAMS IN SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON ALL STREAMS IN SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA dvd_rental.bronze TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA dvd_rental.bronze TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN SCHEMA dvd_rental.bronze TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA dvd_rental.bronze TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA dvd_rental.silver TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA dvd_rental.gold TO ROLE TuanTD24_ROLE;
GRANT ALL PRIVILEGES ON INTEGRATION S3_DVD_RENTAL_INTEGRATION TO ROLE TuanTD24_ROLE;
-- -------------------------------------------------------------------------------------------
GRANT ROLE TuanTD24_ROLE TO ROLE DUCPB7_ROLE;
GRANT ROLE TuanTD24_ROLE to ROLE ACCOUNTADMIN;
GRANT ROLE DucPB7_ROLE to ROLE ACCOUNTADMIN;
-- --------------------------------------------------------------------------------------------
GRANT ROLE TuanTD24_ROLE TO USER TuanTD24;
GRANT ROLE DucPB7_ROLE TO USER DucPB7;

SHOW GRANTS TO ROLE DUCPB7_ROLE;
SHOW GRANTS TO ROLE TuanTD24_ROLE;
-- REVOKE ROLE DUCPB7_ROLE FROM ROLE TuanTD24_ROLE;
