-- Tạo roles
CREATE ROLE IF NOT EXISTS TuanTD24_ROLE;
CREATE ROLE IF NOT EXISTS DucPB7_ROLE;

-- Tạo users (khuyến nghị dùng KEY-PAIR thay vì password nếu có thể)
CREATE OR REPLACE USER TuanTD24
  PASSWORD = 'supernova'
  DEFAULT_ROLE = TuanTD24_ROLE
  DEFAULT_WAREHOUSE = TRANSFORMING
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service account for mini project OTJ';

CREATE OR REPLACE USER DucPB7
  PASSWORD = 'bigbang'
  DEFAULT_ROLE = DucPB7_ROLE
  DEFAULT_WAREHOUSE = TRANSFORMING
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service account for mini project OTJ';

create warehouse transforming; 
create database dvd_rental; 

GRANT ROLE TuanTD24_ROLE TO USER TuanTD24;
GRANT ROLE DucPB7_ROLE TO USER DucPB7;

GRANT USAGE ON DATABASE dvd_rental TO ROLE DucPB7_ROLE;
GRANT USAGE ON DATABASE dvd_rental TO ROLE TuanTD24_ROLE;
GRANT CREATE SCHEMA ON DATABASE dvd_rental TO ROLE DucPB7_ROLE;
GRANT CREATE SCHEMA ON DATABASE dvd_rental TO ROLE TuanTD24_ROLE;