sources:
  - name: bronze
    database: dvd_rental
    schema: bronze
    tables:
      - name: category_strm
      - name: film_category_strm
      - name: film_strm
      - name: payment_strm
      - name: film_actor_strm
      - name: customer_strm
      - name: address_strm
      - name: staff_strm
      - name: city_strm
      - name: country_strm
      - name: actor_strm
      - name: rental_strm
      - name: language_strm
      - name: inventory_strm
      - name: store_strm
